/**
 * Generates the API reference for `@vue/apollo-components`.
 *
 * api-extractor and typedoc both work off `.d.ts`, which for an SFC is the compiler's
 * `__VLS_` shape rather than anything readable. `vue-component-meta` runs the same
 * analysis `vue-tsc` does, so props, events and slots come out with their JSDoc attached.
 */

import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { createChecker } from 'vue-component-meta'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const docsDir = path.resolve(__dirname, '..')
const componentsDir = path.resolve(docsDir, '../vue-apollo-components')
const outDir = path.join(docsDir, 'api/components')

const COMPONENTS = [
  'ApolloQuery',
  'ApolloMutation',
  'ApolloSubscription',
  'ApolloSubscribeToMore',
  'ApolloFragment',
] as const

/**
 * The virtual file the SFC compiles to aliases its imports, so a composable namespace
 * prints as `u.Options`. Each component imports exactly one composable, which makes the
 * expansion unambiguous.
 */
function composableOf(source: string): string | undefined {
  return source.match(/import \{ (use\w+) \} from '@vue\/apollo-composable'/)?.[1]
}

/**
 * `NoInfer` marks a prop as a non-inference site. It says nothing about what may be passed,
 * so it would only puzzle a reader of the table.
 */
function dropNoInfer(type: string): string {
  return type.replace(/\bNoInfer<((?:[^<>]|<[^<>]*>)+)>/g, '$1')
}

/** The rolled-up barrel abbreviates its exports; `R` is the public `RenameKey`. */
const BARREL_ALIASES: Record<string, string> = { R: 'RenameKey' }

/** Short real namespaces the import-alias rewrite below must not swallow. */
const NOT_AN_ALIAS = /^(?:Map|Set|JSX|Vue|Ref)\.$/

function resolveAliases(type: string, source: string): string {
  const resolved = dropNoInfer(type)
    .replace(/\b([A-Z])(?=<)/g, (match, alias: string) => BARREL_ALIASES[alias] ?? match)
  const composable = composableOf(source)
  if (composable == null) {
    return resolved
  }
  return resolved.replace(/\b[A-Za-z_$]{1,3}\.(?=[A-Z])/g, match =>
    NOT_AN_ALIAS.test(match) ? match : `${composable}.`)
}

/**
 * Inlines a local `type X = ...` declared in the SFC.
 *
 * `vue-component-meta` prints such an alias by name, and the reader has no file to look it
 * up in. Long declarations stay abbreviated; expanding them helps nobody.
 */
function resolveLocalAliases(type: string, source: string): string {
  let resolved = type

  for (let pass = 0; pass < 2; pass++) {
    resolved = resolved.replace(/\b[A-Z][\w$]*\b/g, (name) => {
      const declaration = new RegExp(`^type ${name} =([\\s\\S]*?)\\n(?=\\n|type |const |interface )`, 'm').exec(source)
      const inlined = declaration?.[1]
        ?.replace(/\s+/g, ' ')
        .replace(/<\s+/g, '<')
        .replace(/\s+>/g, '>')
        .replace(/\s+,/g, ',')
        .trim()
      return inlined != null && inlined.length <= 160 ? inlined : name
    })
  }

  return resolved
}

/** Placeholder for a table cell with nothing to say, kept visually quieter than a dash. */
const EMPTY = '&nbsp;'

function cell(value: string | undefined) {
  if (!value) {
    return EMPTY
  }
  // A table cell cannot hold a real paragraph break, so keep it as a visible one.
  return value
    .replace(/\|/g, '\\|')
    .replace(/\r?\n\s*\n/g, '<br><br>')
    .replace(/\r?\n/g, ' ')
}

function code(value: string | undefined) {
  return value ? `\`${cell(value)}\`` : EMPTY
}

interface SlotProp { name: string, type: string }

/** `vue-component-meta` reports a slot that takes nothing as `any`. */
function takesNoProps(slot: { type?: string }): boolean {
  return slot.type == null || slot.type === 'any'
}

function slotProps(schema: unknown): SlotProp[] {
  if (typeof schema !== 'object' || schema == null) {
    return []
  }
  const resolved = schema as { kind?: string, schema?: Record<string, { type?: string }> }
  if (resolved.kind !== 'object' || resolved.schema == null) {
    return []
  }
  return Object.entries(resolved.schema).map(([name, value]) => ({
    name,
    type: value.type ?? 'unknown',
  }))
}

function render(name: string, meta: ReturnType<ReturnType<typeof createChecker>['getComponentMeta']>, source: string) {
  const expand = (type: string) => resolveAliases(resolveLocalAliases(type, source), source)
  const composable = composableOf(source)
  const lines: string[] = [
    `# ${name}`,
    '',
    '<!-- Generated by `pnpm api:components`. Do not edit by hand. -->',
    '',
  ]

  const props = meta.props.filter(prop => !prop.global)
  if (props.length > 0) {
    lines.push('## Props', '', '| Name | Type | Default | Description |', '| --- | --- | --- | --- |')
    for (const prop of props) {
      const required = prop.required ? ' *(required)*' : ''
      lines.push(
        `| \`${prop.name}\`${required} | ${code(expand(prop.type))} | ${code(prop.default === 'undefined' ? undefined : prop.default)} | ${cell(prop.description)} |`,
      )
    }
    lines.push('')
  }

  if (meta.events.length > 0) {
    lines.push('## Events', '', '| Name | Payload |', '| --- | --- |')
    for (const event of meta.events) {
      lines.push(`| \`${event.name}\` | ${code(expand(event.type))} |`)
    }
    lines.push('')
  }

  if (meta.slots.length > 0) {
    lines.push('## Slots', '')
    for (const slot of meta.slots) {
      lines.push(`### \`#${slot.name}\``, '')
      if (slot.description) {
        lines.push(slot.description, '')
      }
      const scoped = slotProps(slot.schema)
      if (scoped.length > 0) {
        lines.push('| Slot prop | Type |', '| --- | --- |')
        for (const prop of scoped) {
          lines.push(`| \`${prop.name}\` | ${code(expand(prop.type))} |`)
        }
      }
      else if (takesNoProps(slot)) {
        lines.push('No slot props.')
      }
      else {
        // A union of shapes has no single table, so name the type rather than claim none.
        const type = expand(slot.type)
        lines.push(`Receives ${code(type)}.`)
        if (composable != null && type.includes(`${composable}.Current`)) {
          lines.push(
            '',
            `Every field of [\`${composable}.Current\`](/api/composable/@vue/namespaces/${composable}/interfaces/Current) is present, so \`resultState\` narrows \`result\` here exactly as it does in script.`,
          )
        }
      }
      lines.push('')
    }
  }

  // `vue-component-meta` cannot read `defineExpose` from a generic SFC, and the exposed
  // surface is the composable's result anyway, so link it rather than duplicate it.
  if (composable != null) {
    lines.push(
      '## Exposed',
      '',
      `A template ref receives the full [\`${composable}.Result\`](/api/composable/@vue/namespaces/${composable}/interfaces/Result) surface, with refs unwrapped.`,
      '',
      '```vue',
      '<template>',
      `  <${name} ref="apollo" ... />`,
      '</template>',
      '```',
      '',
    )
  }

  return `${lines.join('\n').trimEnd()}\n`
}

function generate() {
  const checker = createChecker(path.join(componentsDir, 'tsconfig.lib.json'), {
    forceUseTs: true,
    schema: { ignore: [] },
  })

  fs.mkdirSync(outDir, { recursive: true })

  for (const name of COMPONENTS) {
    const file = path.join(componentsDir, 'src', `${name}.vue`)
    const source = fs.readFileSync(file, 'utf-8')
    const meta = checker.getComponentMeta(file)
    fs.writeFileSync(path.join(outDir, `${name}.md`), render(name, meta, source))
    console.log(`  Generated: ${path.relative(docsDir, path.join(outDir, `${name}.md`))}`)
  }

  const index = [
    '# Components API',
    '',
    '<!-- Generated by `pnpm api:components`. Do not edit by hand. -->',
    '',
    ...COMPONENTS.map(name => `- [${name}](./${name})`),
    '',
  ].join('\n')
  fs.writeFileSync(path.join(outDir, 'index.md'), index)
}

console.log('Generating @vue/apollo-components API reference...')
generate()

if (process.exitCode == null) {
  console.log(`Total: ${COMPONENTS.length} components`)
}
